image: alpine:latest

pages:
  stage: deploy
  script:
  - cp participants.json web/
  - cp -R teams web/
  - cd web; python generate-photo-links.py; cd ..
  - cp -r web public
  artifacts:
    paths:
    - public
  only:
  - master
