image: alpine:latest

pages:
  stage: deploy
  script:
  - cp participants.json web/assets/json
  - cp -R teams web/
  - cd web/scripts; python generate-photo-links.py; cd ../..
  - cp -R web public
  artifacts:
    paths:
    - public
  only:
  - master
