image: alpine:latest

pages:
  stage: deploy
  script:
  - cp participants.json public/
  - cp -R teams public/
  - python generate-photo-links.py
  artifacts:
    paths:
    - public
  only:
  - master
