image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir web/
  - cp participants.json web/
  - cp -R teams web/
  - cd web; python generate-photo-links.py
  artifacts:
    paths:
    - web
  only:
  - master
